log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"
    forwardedHeaders:
      trustedIPs:
        - "192.168.0.144/32"

https://gitlab-pe:
  gwdg:
    de/gfbio/submission:
      gfbio:
        org:
          git:

http:
  routers:
    web-secure-router:
      rule: "Host(`submissions.gfbio.org`) || Host(`submission.gfbio.org`) || Host(`denbi-submission.gfbio.dev`)"
      entryPoints:
        - web
      middlewares:
        - csrf
      service: django

    downloads-router:
      rule: "Host(`submissions.gfbio.org`) || Host(`submission.gfbio.org`) && PathPrefix(`/api/downloads/`)"
      entryPoints:
        - web
      service: downloads
      priority: 100

  middlewares:
    redirect:
      # https://docs.traefik.io/master/middlewares/redirectscheme/
      redirectScheme:
        scheme: https
        permanent: true

    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: [ "X-CSRFToken" ]

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    downloads:
      loadBalancer:
        servers:
          - url: http://downloads:5001

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
